# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_12/ConEngineUpdated_c_addsub_0_12.xci
# IP: The module: 'ConEngineUpdated_c_addsub_0_12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_12/ConEngineUpdated_c_addsub_0_12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ConEngineUpdated_c_addsub_0_12'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_12/ConEngineUpdated_c_addsub_0_12.xci
# IP: The module: 'ConEngineUpdated_c_addsub_0_12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_12/ConEngineUpdated_c_addsub_0_12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ConEngineUpdated_c_addsub_0_12'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
