#!/bin/bash -f
# Vivado (TM) v2016.3 (64-bit)
#
# Filename    : ConEngineUpdated.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Feb 07 18:14:38 -0600 2017
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016 
#
# usage: ConEngineUpdated.sh [-help]
# usage: ConEngineUpdated.sh [-lib_map_path]
# usage: ConEngineUpdated.sh [-noclean_files]
# usage: ConEngineUpdated.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'ConEngineUpdated.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "ConEngineUpdated.sh - Script generated by export_simulation (Vivado v2016.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_1/ConEngineUpdated_mult_gen_0_1_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_2/ConEngineUpdated_mult_gen_0_2_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_3/ConEngineUpdated_mult_gen_0_3_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_0/ConEngineUpdated_mult_gen_1_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_4/ConEngineUpdated_mult_gen_0_4_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_1/ConEngineUpdated_mult_gen_1_1_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_2_0/ConEngineUpdated_mult_gen_2_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_3_0/ConEngineUpdated_mult_gen_3_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_5/ConEngineUpdated_mult_gen_0_5_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_2/ConEngineUpdated_mult_gen_1_2_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_6/ConEngineUpdated_mult_gen_0_6_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_3/ConEngineUpdated_mult_gen_1_3_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_7/ConEngineUpdated_mult_gen_0_7_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_4/ConEngineUpdated_mult_gen_1_4_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_8/ConEngineUpdated_mult_gen_0_8_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_5/ConEngineUpdated_mult_gen_1_5_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_9/ConEngineUpdated_mult_gen_0_9_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_6/ConEngineUpdated_mult_gen_1_6_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_10/ConEngineUpdated_mult_gen_0_10_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_7/ConEngineUpdated_mult_gen_1_7_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_11/ConEngineUpdated_mult_gen_0_11_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_8/ConEngineUpdated_mult_gen_1_8_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_12/ConEngineUpdated_mult_gen_0_12_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_9/ConEngineUpdated_mult_gen_1_9_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_13/ConEngineUpdated_mult_gen_0_13_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_10/ConEngineUpdated_mult_gen_1_10_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_14/ConEngineUpdated_mult_gen_0_14_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_11/ConEngineUpdated_mult_gen_1_11_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_15/ConEngineUpdated_mult_gen_0_15_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_12/ConEngineUpdated_mult_gen_1_12_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_16/ConEngineUpdated_mult_gen_0_16_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_13/ConEngineUpdated_mult_gen_1_13_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_17/ConEngineUpdated_mult_gen_0_17_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_14/ConEngineUpdated_mult_gen_1_14_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_18/ConEngineUpdated_mult_gen_0_18_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_15/ConEngineUpdated_mult_gen_1_15_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_19/ConEngineUpdated_mult_gen_0_19_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_16/ConEngineUpdated_mult_gen_1_16_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_20/ConEngineUpdated_mult_gen_0_20_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_17/ConEngineUpdated_mult_gen_1_17_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_21/ConEngineUpdated_mult_gen_0_21_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_18/ConEngineUpdated_mult_gen_1_18_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_22/ConEngineUpdated_mult_gen_0_22_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_19/ConEngineUpdated_mult_gen_1_19_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_23/ConEngineUpdated_mult_gen_0_23_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_20/ConEngineUpdated_mult_gen_1_20_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_24/ConEngineUpdated_mult_gen_0_24_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_21/ConEngineUpdated_mult_gen_1_21_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_25/ConEngineUpdated_mult_gen_0_25_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_1/ConEngineUpdated_c_addsub_0_1_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_2/ConEngineUpdated_c_addsub_0_2_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_3/ConEngineUpdated_c_addsub_0_3_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_4/ConEngineUpdated_c_addsub_0_4_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_5/ConEngineUpdated_c_addsub_0_5_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_6/ConEngineUpdated_c_addsub_0_6_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_7/ConEngineUpdated_c_addsub_0_7_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_8/ConEngineUpdated_c_addsub_0_8_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_9/ConEngineUpdated_c_addsub_0_9_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_10/ConEngineUpdated_c_addsub_0_10_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_11/ConEngineUpdated_c_addsub_0_11_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_12/ConEngineUpdated_c_addsub_0_12_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_13/ConEngineUpdated_c_addsub_0_13_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_14/ConEngineUpdated_c_addsub_0_14_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_15/ConEngineUpdated_c_addsub_0_15_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_16/ConEngineUpdated_c_addsub_0_16_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_17/ConEngineUpdated_c_addsub_0_17_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_18/ConEngineUpdated_c_addsub_0_18_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_19/ConEngineUpdated_c_addsub_0_19_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_20/ConEngineUpdated_c_addsub_0_20_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_21/ConEngineUpdated_c_addsub_0_21_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_22/ConEngineUpdated_c_addsub_0_22_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_23/ConEngineUpdated_c_addsub_0_23_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_24/ConEngineUpdated_c_addsub_0_24_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_25/ConEngineUpdated_c_addsub_0_25_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_20_0/ConEngineUpdated_c_addsub_20_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_21_0/ConEngineUpdated_c_addsub_21_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_22_0/ConEngineUpdated_c_addsub_22_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_23_0/ConEngineUpdated_c_addsub_23_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_24_0/ConEngineUpdated_c_addsub_24_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_25_0/ConEngineUpdated_c_addsub_25_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_26_0/ConEngineUpdated_c_addsub_26_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_27_0/ConEngineUpdated_c_addsub_27_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_28_0/ConEngineUpdated_c_addsub_28_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_32_0/ConEngineUpdated_c_addsub_32_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_32_1/ConEngineUpdated_c_addsub_32_1_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_28_1/ConEngineUpdated_c_addsub_28_1_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_0/ConEngineUpdated_c_addsub_36_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_1/ConEngineUpdated_c_addsub_36_1_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_2/ConEngineUpdated_c_addsub_36_2_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_3/ConEngineUpdated_c_addsub_36_3_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_4/ConEngineUpdated_c_addsub_36_4_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_5/ConEngineUpdated_c_addsub_36_5_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_0/ConEngineUpdated_c_addsub_42_0_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_1/ConEngineUpdated_c_addsub_42_1_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_2/ConEngineUpdated_c_addsub_42_2_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_3/ConEngineUpdated_c_addsub_42_3_sim_netlist.v" \
    "$ref_dir/c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_4/ConEngineUpdated_c_addsub_42_4_sim_netlist.v" \
    "$ref_dir/../../../bd/ConEngineUpdated/hdl/ConEngineUpdated.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.ConEngineUpdated xil_defaultlib.glbl -o ConEngineUpdated_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./ConEngineUpdated_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./ConEngineUpdated.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key ConEngineUpdated_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc ConEngineUpdated_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./ConEngineUpdated.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: ConEngineUpdated.sh [-help]\n\
Usage: ConEngineUpdated.sh [-lib_map_path]\n\
Usage: ConEngineUpdated.sh [-reset_run]\n\
Usage: ConEngineUpdated.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
