# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/saina/Desktop/SeniorDesign/Ip_Try1/Ip_Try1.srcs/sources_1/bd/design_1/ip/design_1_myip_0_0/design_1_myip_0_0.xci
# IP: The module: 'design_1_myip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/saina/Desktop/SeniorDesign/Ip_Try1/Ip_Try1.srcs/sources_1/bd/design_1/ip/design_1_myip_0_0/src/mult_gen_1/mult_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1}]

# IP: c:/Users/saina/Desktop/SeniorDesign/Ip_Try1/Ip_Try1.srcs/sources_1/bd/design_1/ip/design_1_myip_0_0/src/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0}]

# IP: c:/Users/saina/Desktop/SeniorDesign/Ip_Try1/Ip_Try1.srcs/sources_1/bd/design_1/ip/design_1_myip_0_0/design_1_myip_0_0.xci
# IP: The module: 'design_1_myip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/saina/Desktop/SeniorDesign/Ip_Try1/Ip_Try1.srcs/sources_1/bd/design_1/ip/design_1_myip_0_0/src/mult_gen_1/mult_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1}]

# IP: c:/Users/saina/Desktop/SeniorDesign/Ip_Try1/Ip_Try1.srcs/sources_1/bd/design_1/ip/design_1_myip_0_0/src/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0}]
