# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_21/ConEngineUpdated_mult_gen_0_21.xci
# IP: The module: 'ConEngineUpdated_mult_gen_0_21' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_21/ConEngineUpdated_mult_gen_0_21_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ConEngineUpdated_mult_gen_0_21'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_21/ConEngineUpdated_mult_gen_0_21.xci
# IP: The module: 'ConEngineUpdated_mult_gen_0_21' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_21/ConEngineUpdated_mult_gen_0_21_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ConEngineUpdated_mult_gen_0_21'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
