vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -work xil_defaultlib -64 -incr \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_1/ConEngineUpdated_mult_gen_0_1_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_2/ConEngineUpdated_mult_gen_0_2_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_3/ConEngineUpdated_mult_gen_0_3_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_0/ConEngineUpdated_mult_gen_1_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_4/ConEngineUpdated_mult_gen_0_4_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_1/ConEngineUpdated_mult_gen_1_1_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_2_0/ConEngineUpdated_mult_gen_2_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_3_0/ConEngineUpdated_mult_gen_3_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_5/ConEngineUpdated_mult_gen_0_5_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_2/ConEngineUpdated_mult_gen_1_2_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_6/ConEngineUpdated_mult_gen_0_6_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_3/ConEngineUpdated_mult_gen_1_3_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_7/ConEngineUpdated_mult_gen_0_7_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_4/ConEngineUpdated_mult_gen_1_4_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_8/ConEngineUpdated_mult_gen_0_8_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_5/ConEngineUpdated_mult_gen_1_5_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_9/ConEngineUpdated_mult_gen_0_9_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_6/ConEngineUpdated_mult_gen_1_6_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_10/ConEngineUpdated_mult_gen_0_10_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_7/ConEngineUpdated_mult_gen_1_7_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_11/ConEngineUpdated_mult_gen_0_11_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_8/ConEngineUpdated_mult_gen_1_8_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_12/ConEngineUpdated_mult_gen_0_12_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_9/ConEngineUpdated_mult_gen_1_9_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_13/ConEngineUpdated_mult_gen_0_13_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_10/ConEngineUpdated_mult_gen_1_10_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_14/ConEngineUpdated_mult_gen_0_14_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_11/ConEngineUpdated_mult_gen_1_11_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_15/ConEngineUpdated_mult_gen_0_15_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_12/ConEngineUpdated_mult_gen_1_12_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_16/ConEngineUpdated_mult_gen_0_16_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_13/ConEngineUpdated_mult_gen_1_13_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_17/ConEngineUpdated_mult_gen_0_17_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_14/ConEngineUpdated_mult_gen_1_14_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_18/ConEngineUpdated_mult_gen_0_18_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_15/ConEngineUpdated_mult_gen_1_15_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_19/ConEngineUpdated_mult_gen_0_19_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_16/ConEngineUpdated_mult_gen_1_16_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_20/ConEngineUpdated_mult_gen_0_20_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_17/ConEngineUpdated_mult_gen_1_17_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_21/ConEngineUpdated_mult_gen_0_21_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_18/ConEngineUpdated_mult_gen_1_18_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_22/ConEngineUpdated_mult_gen_0_22_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_19/ConEngineUpdated_mult_gen_1_19_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_23/ConEngineUpdated_mult_gen_0_23_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_20/ConEngineUpdated_mult_gen_1_20_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_24/ConEngineUpdated_mult_gen_0_24_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_1_21/ConEngineUpdated_mult_gen_1_21_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_mult_gen_0_25/ConEngineUpdated_mult_gen_0_25_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_1/ConEngineUpdated_c_addsub_0_1_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_2/ConEngineUpdated_c_addsub_0_2_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_3/ConEngineUpdated_c_addsub_0_3_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_4/ConEngineUpdated_c_addsub_0_4_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_5/ConEngineUpdated_c_addsub_0_5_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_6/ConEngineUpdated_c_addsub_0_6_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_7/ConEngineUpdated_c_addsub_0_7_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_8/ConEngineUpdated_c_addsub_0_8_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_9/ConEngineUpdated_c_addsub_0_9_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_10/ConEngineUpdated_c_addsub_0_10_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_11/ConEngineUpdated_c_addsub_0_11_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_12/ConEngineUpdated_c_addsub_0_12_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_13/ConEngineUpdated_c_addsub_0_13_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_14/ConEngineUpdated_c_addsub_0_14_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_15/ConEngineUpdated_c_addsub_0_15_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_16/ConEngineUpdated_c_addsub_0_16_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_17/ConEngineUpdated_c_addsub_0_17_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_18/ConEngineUpdated_c_addsub_0_18_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_19/ConEngineUpdated_c_addsub_0_19_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_20/ConEngineUpdated_c_addsub_0_20_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_21/ConEngineUpdated_c_addsub_0_21_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_22/ConEngineUpdated_c_addsub_0_22_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_23/ConEngineUpdated_c_addsub_0_23_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_24/ConEngineUpdated_c_addsub_0_24_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_0_25/ConEngineUpdated_c_addsub_0_25_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_20_0/ConEngineUpdated_c_addsub_20_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_21_0/ConEngineUpdated_c_addsub_21_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_22_0/ConEngineUpdated_c_addsub_22_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_23_0/ConEngineUpdated_c_addsub_23_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_24_0/ConEngineUpdated_c_addsub_24_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_25_0/ConEngineUpdated_c_addsub_25_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_26_0/ConEngineUpdated_c_addsub_26_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_27_0/ConEngineUpdated_c_addsub_27_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_28_0/ConEngineUpdated_c_addsub_28_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_32_0/ConEngineUpdated_c_addsub_32_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_32_1/ConEngineUpdated_c_addsub_32_1_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_28_1/ConEngineUpdated_c_addsub_28_1_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_0/ConEngineUpdated_c_addsub_36_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_1/ConEngineUpdated_c_addsub_36_1_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_2/ConEngineUpdated_c_addsub_36_2_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_3/ConEngineUpdated_c_addsub_36_3_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_4/ConEngineUpdated_c_addsub_36_4_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_36_5/ConEngineUpdated_c_addsub_36_5_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_0/ConEngineUpdated_c_addsub_42_0_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_1/ConEngineUpdated_c_addsub_42_1_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_2/ConEngineUpdated_c_addsub_42_2_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_3/ConEngineUpdated_c_addsub_42_3_sim_netlist.v" \
"c:/Users/saina/ConvolutionEngineUpdated/ConvolutionEngineUpdated.srcs/sources_1/bd/ConEngineUpdated/ip/ConEngineUpdated_c_addsub_42_4/ConEngineUpdated_c_addsub_42_4_sim_netlist.v" \
"../../../bd/ConEngineUpdated/hdl/ConEngineUpdated.v" \


vlog -work xil_defaultlib "glbl.v"

