# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/saina/Desktop/SeniorDesign/Top_Module/Top_Module.cache/wt [current_project]
set_property parent.project_path C:/Users/saina/Desktop/SeniorDesign/Top_Module/Top_Module.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_cache_permissions disable [current_project]
add_files -quiet c:/Users/saina/Desktop/SeniorDesign/Top_Module/Top_Module.srcs/sources_1/ip/mult_gen_0_2/mult_gen_0.dcp
set_property used_in_implementation false [get_files c:/Users/saina/Desktop/SeniorDesign/Top_Module/Top_Module.srcs/sources_1/ip/mult_gen_0_2/mult_gen_0.dcp]
add_files -quiet c:/Users/saina/Desktop/SeniorDesign/Top_Module/Top_Module.srcs/sources_1/ip/mult_gen_1_1/mult_gen_1.dcp
set_property used_in_implementation false [get_files c:/Users/saina/Desktop/SeniorDesign/Top_Module/Top_Module.srcs/sources_1/ip/mult_gen_1_1/mult_gen_1.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/saina/Desktop/SeniorDesign/T_Flip_Flop/T_Flip_Flop.srcs/sources_1/new/TFlipFlop.v
  C:/Users/saina/Desktop/SeniorDesign/Register_Slices/Register_Slices.srcs/sources_1/new/Reg.v
  C:/Users/saina/Desktop/SeniorDesign/Final_FifoBuffers/Fifo_Buffers.srcs/sources_1/new/FifoTesting.v
  C:/Users/saina/Desktop/SeniorDesign/ConEngine_Verilog/ConEngine_Verilog.srcs/sources_1/new/ConvolutionEngine.v
  C:/Users/saina/Desktop/SeniorDesign/Division/Division.srcs/sources_1/new/Divide.v
  C:/Users/saina/Desktop/SeniorDesign/Top_Module/Top_Module.srcs/sources_1/new/TopLevel_Convolution.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top TopLevel_Convolution -part xc7z020clg484-1


write_checkpoint -force -noxdef TopLevel_Convolution.dcp

catch { report_utilization -file TopLevel_Convolution_utilization_synth.rpt -pb TopLevel_Convolution_utilization_synth.pb }
